export enum DomainExceptionCode {
	DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
	SYSTEM_NAME_REQUIRED = 'SYSTEM_NAME_REQUIRED',
	SYSTEM_DESCRIPTION_REQUIRED = 'SYSTEM_DESCRIPTION_REQUIRED',
	SYSTEM_URL_REQUIRED = 'SYSTEM_URL_REQUIRED',
	SYSTEM_URL_INVALID = 'SYSTEM_URL_INVALID',
	SYSTEM_CLASS_CSS_REQUIRED = 'SYSTEM_PASSWORD_REQUIRED',
	SYSTEM_NOT_FOUND = 'SYSTEM_NOT_FOUND',
}
